# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(850, 699)
        MainWindow.setMinimumSize(QtCore.QSize(850, 699))
        MainWindow.setMaximumSize(QtCore.QSize(850, 699))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(700, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.run_button.setFont(font)
        self.run_button.setStyleSheet("color:white; background-color:rgb(56, 109, 255)")
        
        self.run_button.setObjectName("run_button")
        self.background_1 = QtWidgets.QFrame(self.centralwidget)
        self.background_1.setGeometry(QtCore.QRect(40, 140, 321, 321))
        self.background_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.background_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.background_1.setLineWidth(5)
        self.background_1.setMidLineWidth(2)
        self.background_1.setObjectName("background_1")
        self.input_show = QtWidgets.QLabel(self.background_1)
        self.input_show.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.input_show.setScaledContents(True)
        self.input_show.setObjectName("input_show")
        self.open_fold = QtWidgets.QPushButton(self.centralwidget)
        self.open_fold.setGeometry(QtCore.QRect(60, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas-with-Yahei")
        font.setPointSize(12)
        self.open_fold.setFont(font)
        self.open_fold.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.open_fold.setAutoDefault(False)
        self.open_fold.setObjectName("open_fold")
        self.img_list = QtWidgets.QComboBox(self.centralwidget)
        self.img_list.setGeometry(QtCore.QRect(290, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas-with-Yahei")
        font.setPointSize(12)
        self.img_list.setFont(font)
        self.img_list.setObjectName("img_list")
        self.background_3 = QtWidgets.QFrame(self.centralwidget)
        self.background_3.setGeometry(QtCore.QRect(30, 520, 801, 121))
        self.background_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.background_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.background_3.setLineWidth(5)
        self.background_3.setMidLineWidth(2)
        self.background_3.setObjectName("background_3")
        self.result_show = QtWidgets.QLabel(self.background_3)
        self.result_show.setGeometry(QtCore.QRect(10, 10, 781, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas-with-Yahei")
        font.setPointSize(10)
        self.result_show.setFont(font)
        self.result_show.setText("")
        self.result_show.setObjectName("result_show")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 480, 71, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.model_list = QtWidgets.QComboBox(self.centralwidget)
        self.model_list.setGeometry(QtCore.QRect(500, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas-with-Yahei")
        font.setPointSize(12)
        self.model_list.setFont(font)
        self.model_list.setCurrentText("")
        self.model_list.setObjectName("model_list")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 861, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setMouseTracking(False)
        self.title.setStyleSheet("background:rgb(255, 242, 167)")
        self.title.setObjectName("title")
        self.background_2 = QtWidgets.QFrame(self.centralwidget)
        self.background_2.setGeometry(QtCore.QRect(490, 140, 321, 321))
        self.background_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.background_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.background_2.setLineWidth(5)
        self.background_2.setMidLineWidth(2)
        self.background_2.setObjectName("background_2")
        self.output_show = QtWidgets.QLabel(self.background_2)
        self.output_show.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.output_show.setScaledContents(True)
        self.output_show.setObjectName("output_show")
        self.pre_img_button = QtWidgets.QPushButton(self.centralwidget)
        self.pre_img_button.setGeometry(QtCore.QRect(380, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pre_img_button.setFont(font)
        self.pre_img_button.setObjectName("pre_img_button")
        self.next_img_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_img_button.setGeometry(QtCore.QRect(380, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.next_img_button.setFont(font)
        self.next_img_button.setObjectName("next_img_button")
        self.switch_show = QtWidgets.QPushButton(self.centralwidget)
        self.switch_show.setGeometry(QtCore.QRect(380, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.switch_show.setFont(font)
        self.switch_show.setObjectName("switch_show")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.open_mask = QtWidgets.QPushButton(self.centralwidget)
        self.open_mask.setGeometry(QtCore.QRect(160, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas-with-Yahei")
        font.setPointSize(12)
        self.open_mask.setFont(font)
        self.open_mask.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.open_mask.setAutoDefault(False)
        self.open_mask.setObjectName("open_mask")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 79, 211, 51))
        self.frame.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.run_button.raise_()
        self.background_1.raise_()
        self.open_fold.raise_()
        self.img_list.raise_()
        self.background_3.raise_()
        self.label_4.raise_()
        self.model_list.raise_()
        self.title.raise_()
        self.background_2.raise_()
        self.pre_img_button.raise_()
        self.next_img_button.raise_()
        self.switch_show.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.open_mask.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "龋病分级检测平台"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.open_fold.setText(_translate("MainWindow", "选择图片"))
        self.label_4.setText(_translate("MainWindow", "诊断结果："))
        self.title.setText(_translate("MainWindow", "                  龋病分级检测平台"))
        self.pre_img_button.setText(_translate("MainWindow", "上一张"))
        self.next_img_button.setText(_translate("MainWindow", "下一张"))
        self.switch_show.setText(_translate("MainWindow", "原图/标签"))
        self.label_8.setText(_translate("MainWindow", "图片列表"))
        self.label_9.setText(_translate("MainWindow", "模型列表"))
        self.open_mask.setText(_translate("MainWindow", "选择标签"))
    
    def backEnd(self, MainWindow):
        self.run_button.clicked.connect(MainWindow.inference)
        self.open_fold.clicked.connect(MainWindow.openFold)
        self.open_mask.clicked.connect(MainWindow.openMask)
        self.pre_img_button.clicked.connect(MainWindow.priorImage)
        self.next_img_button.clicked.connect(MainWindow.nextImage)
        self.switch_show.clicked.connect(MainWindow.inference)
        self.img_list.activated.connect(MainWindow.chooseFile)
        self.model_list.activated.connect(MainWindow.chooseModel)

